### ISSUE TITLE
Mehr On-demand info 

### ISSUE THREAD

**Issue by ewerybody** [rhein-main-swingtime/frontend-hugo#102]
.. weniger "default-wall-of-text"
Gerade müssen wir auf der Tanzen-Seite in der Mobile-Ansicht ersma 1 1/2 Seiten scrollen bis nen event kommt:
> current:
> ![image](https://user-images.githubusercontent.com/218956/163673987-2115980d-af24-47c0-b6e7-a44459025a43.png)

Ich finds sehr GUT, dass es zu jeder Seite nen Intro-text gibt aber den sollte man vielleicht nur einmal standardmäßig zu sehen bekommen ansonsten mit Klick auf nen `?` oder `!`-Symbol oder so. Was meinste @mafeka ?

> Vorschlag, gleich mit eingeklapptem Filter:
> ![image](https://user-images.githubusercontent.com/218956/163674706-10f32224-1e49-47d2-b6ff-f976ec3d6f71.png)

**Comment by mafeka** [comment]
Ja, da ist was dran. Mit diesen Info-Boxen bzw. Notifications bin ich auch noch nicht so ganz happy. 

Einfach Lösung wäre vermutlich direkt unter der Headline ("Komm tanzen"), einen Link unterzubringen, der runter zu dein eigentlichen Events führt.
