### ISSUE TITLE
Makes "Lehrer" gender neutral

### ISSUE THREAD

**Issue by mafeka** [rhein-main-swingtime/frontend-hugo#120]
Hey,
Hinweis von Lindy bekommen, das sie lieber Lehrerin heissen will. Finde da hat sie recht, können wir auch gleich richtig durchziehen.

**Comment by mafeka** [comment]
Hey @ewerybody,
schau mal rein, passt für dich?

**Comment by ewerybody** [comment]
Ohje 🙈. Da haben wir noch einiges vor uns. Ich habs am liebsten wenn man das Geschlecht komplett weglassen kann. Weils meist auch nicht darum geht, dass jene Person ein geschlecht hat sondern, dass sie dies oder das tut!
"Lehrkraft" is aber auch blöd. 

In dem Zuge schlüge ich noch ein paar andere Sachen vor. "Künstler" sollte zB wieder "Musik" heißen.
What's more? 🤔

**Comment by ewerybody** [comment]
Ich hab noch ein paar sachen in den branch committed

**Comment by mafeka** [comment]
Hey,
erst mal vielen Dank für die ganzen Korrekturen, mega!

> Ohje 🙈. Da haben wir noch einiges vor uns. Ich habs am liebsten wenn man das Geschlecht komplett weglassen kann. 

Ja, da bin ich im Prinzip bei. Finde aber tatsächlich `Lehrer:innen` oder `Musiker:innen` deutlich besser als `Lehrende` und (wut?) `Musizierende`. Das liest sich ja als wäre das eine Dauertätigkeit. Jemand kann ist halt Lehrer oder Lehrerin. Daher würde ich das bei der Musik-Seite auch so schreiben. Können wir gerne in `Musik` zurückumbenennen aber lass uns die `Musiker:innen` wieder rein nehmen.

**Comment by mafeka** [comment]
Eben erst gesehen, sind einige Stellen, die du angepasst hast. Also meins ist es überhaupt nicht mit den Dauertätigkeiten, aber wenn es dir wichtig ist, passt das für mich auch so.

**Comment by ewerybody** [comment]
Einige Stellen? [Hier is die einzige Stelle](https://github.com/rhein-main-swingtime/frontend-hugo/pull/121/commits/550d057d29447fc6e9bd4606585b6485505449fe#diff-81c689d54ac2444fa6493a19d3efc3a5a2d0fb11fd8a663ed2f859c46b4bc21c) wo ich "Lehrende" schrieb.

Ich hab **nirgends** "Musizierende" geschrieben! Das klingt für mein Ohr auch doof.

**Comment by mafeka** [comment]
Nicht falsch verstehen, wollte weder nörgeln noch irgendwas bekritteln :) Eher im Gegenteil, ist offensichtlich ordentlich Mühe rein geflossen und daher fettes Danke :)

"Musizierende" sollte mehr ein Scherz sein, um einen Grund zu verdeutlichen, warum ich die Art und Weise zu genderneutraler Sprache zu kommen, manchmal bisschen seltsam finde.

Ich meine konkret eher solche Stellen wie diese hier: https://github.com/rhein-main-swingtime/frontend-hugo/pull/121/files?short_path=a2b8403#diff-a2b840321587caf14f50264156ee21b6b62747e426543056ac388bf603c0503f

Da ist der "geschlechtsbehaftete" Begriff "Musiker" rausgeflogen. 

Also wie gesagt, ich bin komplett fein damit - das wo es geht - entsprechend umzuschreiben, da wo es nicht elegant geht würde ich dann die Doppelpunkt-Schreibweise bevorzugen anstatt den Umweg darüber es als Tätigkeit zu formulieren.

Kommende Woche kann ich da ggf. auch noch mal bisschen Zeit investieren, aber das was du hier rein gepackt hast, sieht schon mal echt super aus!

**Comment by ewerybody** [comment]
Hey Felix! Okok.
Na, ich will nicht behaupten, das Thema komplett verinnerlicht zu haben. Amend sind wir hier alte, weiße Männer und alles kann uns zu nem Strick gedreht werden.

Ich würde versuchen diese gender-Sternchen, -Doppelpunkte, -Striche soweit es geht zu vermeiden und ne alternative Formulierung zu benutzen die im besten Fall die **Tätigkeit** oder das **Thema voranstellt**. Denn meistens geht es ja nicht darum, dass besagte Personen diese oder jene Geschlechtszugehörigkeit haben sondern um eine gewisse Sache.
Der Club derer die sich das ganz vorne druffkleben, an jeder sich bietenden Stelle Sternchen verteilen und hintenrum aber Null-Komma-garnix tun wird ständig größer. Natürlich will ich auch nicht in dem Bratwurst-Club bleiben der sich vollkommen verballert dieser Entwicklung versagt und stoisch auf generischem Maskulinum beharrt.
Swing-Tanzen is für mich gelebte Inklusivität und nicht nur Virtue Signaling.

Die "Musizierende"-Lösung is auch nich perfekt. Das stimmt. Aber das is auch ne Trainingssache und fühlt sich bei anderen Begriffen viel normaler an. "Studierende" fand ich auch mal komplett behämmert und mittlerweile denk ich: so what! "Kunstschaffende" las ich am Wochenende erst in der Zeitung und es hat nen Moment gedauert, dass mir das überhaupt aufgefallen is.

Wenn der Platz das nicht hergibt und keinen andere Lösungen passt, können wir gerne _:innen, *innen, Innen, /innen_ nutzen. Auf eine Schreibweise festlegen würde ich mich bewusst nicht sondern explizit alles benutzen.

Am liebsten wär mir sogar das "[Entgendern nach Phettberg](https://de.wikipedia.org/wiki/Hermes_Phettberg#Geschlechtergerechte_Sprache)" für diese Fälle. Das is kompakt und auch noch witzig.
Das benutzen die tatsächlich auch auf [uberspace.de](https://uberspace.de/de/) in ihrem header. Neben der Doppelpunktschreibweise. (Da isses leider nur nen Gimmick und macht beim Umschalten auf Englisch auch nochmal das Affentheater klar das wir hier mit unserer verkorksten Sprache haben)

An der verlinkten Stelle: Wir haben da gerade tatsächlich nur Bands, DJs und gar keine einzelnen Musikys :) Ich dachte für die Eventualität wäre **& Co** ausreichend.

**Comment by mafeka** [comment]
Hey,
> Ich würde versuchen diese gender-Sternchen, -Doppelpunkte, -Striche soweit es geht zu vermeiden und ne alternative Formulierung zu benutzen die im besten Fall die Tätigkeit oder das Thema voranstellt. 

Da hast du völlig recht, am Beispiel der Lernen-Seite könnte man das auch elegant lösen. Kategorie ist dann nicht mehr "Lehrer" sondern "Kurse" oder z.B. "Einzelstunden". Könnten wir eigentlich genauso anpassen.

> Wenn der Platz das nicht hergibt und keinen andere Lösungen passt, können wir gerne :innen, *innen, Innen, /innen nutzen. Auf eine Schreibweise festlegen würde ich mich bewusst nicht sondern explizit alles benutzen.

Fair enough! 👍 

> Am liebsten wär mir sogar das "[Entgendern nach Phettberg](https://de.wikipedia.org/wiki/Hermes_Phettberg#Geschlechtergerechte_Sprache)" für diese Fälle.

Kannte ich noch nicht, aber finde ich geil, bin ich bei!

**Comment by mafeka** [comment]
Wollen wir den PR mal mergen?

**Comment by ewerybody** [comment]
Na wenns geht biegen wir noch zu Musik/Music oder?

**Comment by mafeka** [comment]
> Na wenns geht biegen wir noch zu Musik/Music oder?

Done 👍

**Comment by ewerybody** [comment]
Nice! Ja dann von mir aus! ... 🎢
