### ISSUE TITLE
"Learn/Lernen" Links layout broken

### ISSUE THREAD

**Issue by ewerybody** [rhein-main-swingtime/frontend-hugo#160]
https://rmswing.de/lernen/
![image](https://github.com/rhein-main-swingtime/frontend-hugo/assets/218956/8287277a-14c9-48d8-a861-76ed6d273cd1)
🤔

**Comment by ewerybody** [comment]
In der Zeile hier
https://github.com/rhein-main-swingtime/frontend-hugo/blob/6b12b91b87a32f9d9d1aea61254e77d3612c72db/layouts/partials/learn/item.html#L20
Kommt im Browser das CSS raus: 
```css
grid-template-columns: repeat(12, minmax(0, 1fr));
```
Wenn man das toggelt gehts wieder alles 
![image](https://github.com/rhein-main-swingtime/frontend-hugo/assets/218956/3cc8aa6a-744a-4f82-b54d-0e90d6213f69)

Aber an dem tailwind rundoktorn bringt irgendwie nix. Keine Ahnung wie das zu fixen is 🤷
@mafeka ? HALP!!

**Comment by ewerybody** [comment]
auf der events-seite is auch was verrottet:
![image](https://github.com/rhein-main-swingtime/frontend-hugo/assets/218956/aa626599-860d-42aa-b850-54c5ec76b975)
keine Ahnung ob das nen ähnliches issue is?
Kanns sein, dass durch nen npm/yarn update tailwind nun irgendwie was anderes macht?

**Comment by ewerybody** [comment]
Das mit den X-Buttons is auf mobile auch!
Das mit dem grid auf der lernen-Seite allerdings nicht!

**Comment by mafeka** [comment]
Schau ich mir an. 👍🏻

**Comment by ewerybody** [comment]
Oki ich hab das ma versucht. #230 

Im mobile layout isses OK. Scheint NUR das Desktop zu betreffen.
Da kam auch noch ne mail mitte des Jahres vom Monika-Bauer-Team :)

broken:
![image](https://github.com/user-attachments/assets/b7bd120f-81ce-4faa-85a0-723d269355e2)

"fixed":
![image](https://github.com/user-attachments/assets/0519a11a-d42b-4dda-bfad-7a003b5c6c94)
