### ISSUE TITLE
Matomo

### ISSUE THREAD

**Issue by mafeka** [rhein-main-swingtime/frontend-hugo#32]

**Comment by ewerybody** [comment]
https://translate.google.com/?sl=auto&tl=de&text=Matomo&op=translate ? 🤔

**Comment by mafeka** [comment]
Webanalytics: https://matomo.org/

Will ich mal mit rumspielen und sehen ob wir das anständig anonymisiert
hinbekommen. Komplett eigene Instanz habe ich uns schon aufgesetzt.

Am Fr., 18. Feb. 2022 um 11:48 Uhr schrieb Eric Werner <
***@***.***>:

**Comment by mafeka** [comment]
Habs mir mal genauer angeschaut, imho können wir das gut einsetzen. Lass gerne noch mal drüber sprechen, ich weiss du bist da skeptisch.

Was mir gefallen würde:
- Ist anonym (wir löschen auch das letzte Oktet in der IP)
- Kein Cookie Banner, kein Checkboxen, kein Bullshit
- Respektiert Opt-Out Browser Einstellungen
- Auch noch mal expliziter Opt-Out möglich
- Wir kriegen Eindruck davon wie unsere Reichweite ist und was die Leute auf der Seite benutzen (z.B. Eventpage-Filter, Kategorien, generell die Filter, ...). Wir können Access Logs im Server im Prinzip komplett aus lassen, sind wir an dem Ende Datensparsam.
