### ISSUE TITLE
Alternative Logo for Header Navi

### ISSUE THREAD

**Issue by mafeka** [rhein-main-swingtime/frontend-hugo#46]
Hey @ewerybody,
Lust uns mal eine Logo Version für den Header zu basteln, die etwas schmaler ist?

Sieht auf Tablet (and above) aktuell so aus:

![image](https://user-images.githubusercontent.com/15047524/154863044-eba287ed-b47b-4d43-a3fb-3f510f715290.png)

Denke bisschen schmaler könnte man da optisch werden und ich kann sowas nicht 🤷  Einfachste Variante wäre vermutlich einfach "RMST" zu nehmen, aber i dont know...

**Comment by ewerybody** [comment]
das sieht doch super aus. Hab mich schon dran gewöhnt. Für alle anderen Fälle haben wir aber noch das Favicon was aber nur in Ausnahmefällen benutzt werden sollte.
