### ISSUE TITLE
Kurskalender Sunny Side Swing Darmstadt inkludieren

### ISSUE THREAD

**Issue by vivew** [rhein-main-swingtime/frontend-hugo#77]
Die Kurse werden in folgendem Kalender gepflegt: https://calendar.google.com/calendar/u/0?cid=c3VubnlzaWRlc3dpbmdzdHVkaW9AZ21haWwuY29t

Kann er inkludiert werden?

**Comment by ewerybody** [comment]
Hmm das machen wir hier schon https://rmswing.de/en/classes 
Keine Ahnung woraus diese classes events in der Ansicht gefüttert werden.

Zusätzlich müssen wir das noch in der neuen Liste auflösen, was? 🤔
Vielleicht diese embedd-Links auch bei https://github.com/rhein-main-swingtime/frontend-hugo/blob/main/data/learn.yml einbauen und zum klicken anbieten?

**Comment by mafeka** [comment]
Hey,
den Kalender habe ich inkludiert, erscheint jetzt auch in der Liste der Events:

https://hugo.rmswing.de/tanzen/?events::&calendar[]=Sunny%20Side%20Swing&calendar[]=Social%20Time

An einer Verknüpfung von der Lernen Seite zu den Events arbeite ich noch, ist aber kein Quickfix (#79) :)
