### ISSUE TITLE
Sunny Side Swing Infos ergänzen

### ISSUE THREAD

**Issue by vivew** [rhein-main-swingtime/frontend-hugo#78]
Für die Tanzschule Sunny Side Swing wären folgende Infos noch super :-)

Adresse:
> Rheinstraße 22
> 64283 Darmstadt

Tel.:
> 01797425147

Facebook:
> https://www.facebook.com/swingindarmstadt/

Instragram:
> https://www.instagram.com/sunnysideswingstudio/

**Comment by ewerybody** [comment]
Nice gingdurch! https://github.com/rhein-main-swingtime/frontend-hugo/actions/runs/1986450267 👍

**Comment by vivew** [comment]
Sehr cool! Der Link zur Karte funktioniert nur leider noch nicht richtig (das scheint auch bei anderen Einträgen ein Problem).
Dieser Link geht: [https://www.google.com/maps/search/?api=1&query=sunny+side+swing+Rheinstrasse+22+64283+Darmstadt](https://www.google.com/maps/search/?api=1&query=sunny+side+swing+Rheinstrasse+22+64283+Darmstadt)

![image](https://user-images.githubusercontent.com/68237361/158489071-e0b519b9-50f1-4708-a76a-f5574f9a055b.png)

**Comment by ewerybody** [comment]
Guter Hinweis! Ich hab da mal nen neues Issue draus gemacht #80 
Also der Balboa-Heiner-Link ging auch GAR nicht! Ich hab mal die Daten mit den Namen ergänzt. 1fd3d2b
das fixt es für die Heiner, aber nicht für Sunny Side Swing. Da streikt Google immernoch wegen den komischen Zeichen. Das is son Hugo-Ding? @mafeka weiß bestimmt mehr :)

Aber wie du siehst speichern wir gar keinen Maps-Link sondern ne Adresse um sie auch in der Card anzuzeigen und werfen dann den Adress-Text auf Maps.
