### ISSUE TITLE
Resolve submenu titles

### ISSUE THREAD

**Issue by ewerybody** [rhein-main-swingtime/frontend-hugo#8]
think deeply about it...
meditate ... 🕉

**Comment by ewerybody** [comment]
* Home
* Social Dances
* Dance Classes
* What?
* Music
* Scene
* Contribute

* Hauptseite
* Veranstaltungen
* Tanzkurse
* Wie Bitte?
* Musik
* Szene
* Mitmachen

**Comment by mafeka** [comment]
> think deeply about it... meditate ... 🕉

Meditation done? :D

**Comment by ewerybody** [comment]
ich hab schon öfter das feedback bekommen, dass "Komm tanzen" unklar is. Antje hatte auch die Idee das "Veranstaltungen" zu nennen. Is weniger kompakt aber ich denke das is besser am end

**Comment by mafeka** [comment]
Finde ich gut, lass machen!
