### ISSUE TITLE
Maps links all broken? What the %5B ?!!

### ISSUE THREAD

**Issue by ewerybody** [rhein-main-swingtime/frontend-hugo#80]
In allen unseren Maps links sind abgefahrene Zeichenfolgen drin zB:

```
%5Bdie+tanzschule+C.+Weber+GmbH+Bolongarostra%C3%9Fe+113+D-65929+Frankfurt%5D
```
Sind das klammern? Wäre schön wenn das schöner ging.

**Comment by ewerybody** [comment]
@mafeka ich habs mal so gebaut, dass die `[]` weg sind. Die links sehen nun so aus:
[...&query=Sunny%2bSide%2bSwing%2bRheinstra%25C3%259Fe%2b22%2b64283%2bDarmstadt](https://www.google.com/maps/search/?api=1&query=Sunny%2bSide%2bSwing%2bRheinstra%25C3%259Fe%2b22%2b64283%2bDarmstadt)
Das funktioniert schon viel besser und es wird alles gefunden. Aber der Suchtext is noch etwas zerballert:
> Sunny+Side+Swing+Rheinstra%C3%9Fe+22+64283+Darmstadt

So wäre ideal: Aber das is nich das was [`querify`](https://gohugo.io/functions/querify/) macht ^
[...&query=Sunny%20Side%20Swing%20Rheinstra%c3%9fe%2022%2064283%20Darmstadt](https://www.google.com/maps/search/?api=1&query=Sunny%20Side%20Swing%20Rheinstra%c3%9fe%2022%2064283%20Darmstadt)

So wird alles gefunden, der Link hat keine spaces und der Suchtext is ok:
> Sunny Side Swing Rheinstraße 22 64283 Darmstadt

Nicht querify-en geht auch! Aber dann haben wir halt spaces in den Links ... 🤔

**Comment by mafeka** [comment]
Hey,
interessant! 

Ich würde da bei `querify` bleiben, sonst sind wir darauf angewiesen, das der Browser mit Spaces umgehen kann (kann nicht jeder). Urls müssen halt generell encoded sein. Wenn du damit rumspielen willst: https://www.urldecoder.org/ oder in der console `decodeURI()`

**Comment by mafeka** [comment]
Hast du dazu noch einen Branch?

**Comment by ewerybody** [comment]
Nee war zu faul für nen branch. Das a919ecf war alles was ich geändert hab.
Ja irgendwas wie `querify` würd ich schon drin lassen. Nur isses wie gezeigt nich ideal.
Vielleicht isses schon besser, wenn wir noch die `%2b` (aka `+` ) mit `%20` replacen? Ach das `ß` hats aber auch nich gepackt, was? ... 🤔 lek..

**Comment by mafeka** [comment]
Also das encoding von Sonderzeichen würde ich auf keinen Fall irgendwie ändern, ist zum Schluss ja auch echt nur Kosmetik. Du kannst dich auch a) nicht darauf verlassen ob das die Google API auf Dauer mitmacht oder b) irgendein Browser Quatschi macht...

Was man aber mal ansehen könnte ist warum da die + auftauchen. 

Vielleicht noch mal durch printf hauen...?

**Comment by mafeka** [comment]
Ich schnapp mir das eben mal.

**Comment by mafeka** [comment]
Ist gefixt, wenn auch nur über JS.
