### ISSUE TITLE
failed to transform "scripts/main.ts" Expected ")" but found ":" 🤷‍♀️

### ISSUE THREAD

**Issue by ewerybody** [rhein-main-swingtime/frontend-hugo#9]
Beim `hugo serve` kommt das für `_default` pages

```js
render of "page" failed:
execute of template failed:
  template: _default/share.html:32:12: executing "_default/share.html" at <partial "footer.html" .>:
  error calling partial: "...\frontend-hugo\layouts\partials\footer.html:3:51":
execute of template failed:
  template: partials/footer.html:3:51: executing "partials/footer.html" at <resources.Concat>:
error calling Concat:
  resources in Concat must be of the same Media Type, got "application/javascript" and "application/typescript"

...

Error: Error building site: JSBUILD: failed to transform "scripts/main.ts" (application/typescript): Expected ")" but found ":"
```
Aber es sagt nicht welche Zeile. Wird nix gehighlighted (Außer `Alpine` hier:)
https://github.com/rhein-main-swingtime/frontend-hugo/blob/39e3a16c580a7e8a6ed25b1497ebc4e4c27fb9af/assets/scripts/main.ts#L41

mein `main.ts` is aber identisch zum dem in main hier :|
HALP

**Comment by mafeka** [comment]
Bist du auf der main branch unterwegs?

**Comment by mafeka** [comment]
Eben mal getestet:
- Main ausgecheckt
- Terminal 1: `yarn development`
- Terminal 2: `hugo serve` 

Sieht okay aus. Falls andere Branch: Mal main rein mergen, `yarn install` und dann s.o.

**Comment by ewerybody** [comment]
neues Hugo ... voilà :)
